package edu.progAvUD.primerTaller2Corte.vista;

/**
 * Clase DialogDatosCorredor que representa un diálogo para ingresar los datos
 * de un corredor. Permite la entrada de nombre, cédula, tipo de corredor, tipo
 * de animal (si aplica) y velocidad máxima. Extiende de javax.swing.JDialog
 * para ser un diálogo modal en la aplicación.
 *
 * @author Andres Felipe
 */
public class DialogDatosCorredor extends javax.swing.JDialog {

    /**
     * Constructor que crea un nuevo diálogo para ingresar datos del corredor.
     * Inicializa los componentes gráficos y centra el diálogo en la pantalla.
     *
     * @param parent La ventana padre que contiene este diálogo.
     * @param modal Define si el diálogo es modal (bloquea interacción con la
     * ventana padre).
     */
    public DialogDatosCorredor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // Centrar el diálogo en la pantalla
    }

    /**
     * Método para limpiar los campos del formulario del diálogo. Resetea los
     * campos de texto, limpia la selección de los botones de radio, reinicia el
     * valor del spinner de velocidad máxima y selecciona el primer ítem del
     * combo box de tipo de animal.
     */
    public void limpiarCampos() {
        // Limpiar selección de los botones de radio
        buttonGroupTipoCorredor.clearSelection();

        // Limpiar los campos de texto
        jTextFieldNombre.setText("");
        jTextFieldCedula.setText("");
        jTextFieldOtroAnimal.setText("");

        // Reiniciar el valor del spinner (por ejemplo, a 0)
        jSpinnerVelocidadMaxima.setValue(0);

        // Reiniciar la selección del combo box (opcionalmente al primer ítem)
        jComboBoxTipoAnimal.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoCorredor = new javax.swing.ButtonGroup();
        jRadioButtonAnimal = new javax.swing.JRadioButton();
        jRadioButtonPersona = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerVelocidadMaxima = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jButtonContinuar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelNumeroCorredor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoAnimal = new javax.swing.JComboBox<>();
        jLabelOtroAnimal = new javax.swing.JLabel();
        jTextFieldOtroAnimal = new javax.swing.JTextField();
        jLabelNotaOtro1 = new javax.swing.JLabel();
        jLabelNotaOtro2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroupTipoCorredor.add(jRadioButtonAnimal);
        jRadioButtonAnimal.setText("Animal");

        buttonGroupTipoCorredor.add(jRadioButtonPersona);
        jRadioButtonPersona.setText("Persona");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Velocidad Maxima Obtenida: ");

        jSpinnerVelocidadMaxima.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Tipo de Animal:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Cedula:");

        jButtonContinuar.setText("Continuar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Digite los datos del corredor No.");

        jLabelNumeroCorredor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNumeroCorredor.setText("1");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("Tipo de Corredor:");

        jComboBoxTipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Periquin", "Aguila", "Caballo", "Caiman", "Cebra", "Elefante", "Gato", "Jaguar", "Leon", "Mono", "OsoPanda", "OsoPerezoso", "Perro", "Tigre", "Tucan", "Otro" }));

        jLabelOtroAnimal.setText("Si es otro, escriba el tipo:");

        jLabelNotaOtro1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelNotaOtro1.setText("Nota: Al escribir \"otro\", la imagen del animal no se vera reflejado en la carrera");

        jLabelNotaOtro2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelNotaOtro2.setText("(se tomara un animal predefinido)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonAnimal)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonPersona))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNumeroCorredor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelOtroAnimal))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jSpinnerVelocidadMaxima)
                                    .addComponent(jTextFieldCedula)
                                    .addComponent(jComboBoxTipoAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOtroAnimal)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelNotaOtro1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabelNotaOtro2)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNumeroCorredor))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAnimal)
                    .addComponent(jRadioButtonPersona)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerVelocidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOtroAnimal)
                    .addComponent(jTextFieldOtroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNotaOtro1)
                .addGap(1, 1, 1)
                .addComponent(jLabelNotaOtro2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButtonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupTipoCorredor;
    public javax.swing.JButton jButtonContinuar;
    public javax.swing.JComboBox<String> jComboBoxTipoAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelNotaOtro1;
    public javax.swing.JLabel jLabelNotaOtro2;
    public javax.swing.JLabel jLabelNumeroCorredor;
    public javax.swing.JLabel jLabelOtroAnimal;
    public javax.swing.JRadioButton jRadioButtonAnimal;
    public javax.swing.JRadioButton jRadioButtonPersona;
    public javax.swing.JSpinner jSpinnerVelocidadMaxima;
    public javax.swing.JTextField jTextFieldCedula;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldOtroAnimal;
    // End of variables declaration//GEN-END:variables
}
