package edu.progAvUD.primerTaller2Corte.vista;

/**
 * Clase PanelCarrera que representa el panel principal donde se visualiza la
 * carrera. Este panel contiene los componentes gráficos necesarios para mostrar
 * la carrera y sus corredores.
 *
 * @author Andres Felipe
 */
public class PanelCarrera extends javax.swing.JPanel {

    /**
     * Constructor por defecto que crea una instancia de PanelCarrera.
     * Inicializa todos los componentes gráficos mediante el método
     * initComponents().
     */
    public PanelCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIniciarCarrera = new javax.swing.JButton();
        jButtonAccidente = new javax.swing.JButton();
        jButtonImpulsar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelCarrera = new PanelConFondo();
        jPanelCorredor1 = new javax.swing.JPanel();
        jLabelImagenCorredor1 = new javax.swing.JLabel();
        jPanelCorredor2 = new javax.swing.JPanel();
        jLabelImagenCorredor2 = new javax.swing.JLabel();
        jPanelCorredor3 = new javax.swing.JPanel();
        jLabelImagenCorredor3 = new javax.swing.JLabel();
        jPanelCorredor4 = new javax.swing.JPanel();
        jLabelImagenCorredor4 = new javax.swing.JLabel();
        jPanelMeta = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonIniciarCarrera.setText("Iniciar Carrera");
        jPanel1.add(jButtonIniciarCarrera);

        jButtonAccidente.setText("Accidente 1");
        jPanel1.add(jButtonAccidente);

        jButtonImpulsar.setText("Impulsar 2");
        jPanel1.add(jButtonImpulsar);

        jButtonSalir.setText("Salir");
        jPanel1.add(jButtonSalir);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanelCorredor1.setOpaque(false);
        jPanelCorredor1.setLayout(new java.awt.BorderLayout());
        jPanelCorredor1.add(jLabelImagenCorredor1, java.awt.BorderLayout.CENTER);

        jPanelCorredor2.setOpaque(false);
        jPanelCorredor2.setLayout(new java.awt.BorderLayout());
        jPanelCorredor2.add(jLabelImagenCorredor2, java.awt.BorderLayout.CENTER);

        jPanelCorredor3.setOpaque(false);
        jPanelCorredor3.setLayout(new java.awt.BorderLayout());
        jPanelCorredor3.add(jLabelImagenCorredor3, java.awt.BorderLayout.CENTER);

        jPanelCorredor4.setOpaque(false);
        jPanelCorredor4.setLayout(new java.awt.BorderLayout());
        jPanelCorredor4.add(jLabelImagenCorredor4, java.awt.BorderLayout.CENTER);

        jPanelMeta.setOpaque(false);

        javax.swing.GroupLayout jPanelMetaLayout = new javax.swing.GroupLayout(jPanelMeta);
        jPanelMeta.setLayout(jPanelMetaLayout);
        jPanelMetaLayout.setHorizontalGroup(
            jPanelMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jPanelMetaLayout.setVerticalGroup(
            jPanelMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCarreraLayout = new javax.swing.GroupLayout(jPanelCarrera);
        jPanelCarrera.setLayout(jPanelCarreraLayout);
        jPanelCarreraLayout.setHorizontalGroup(
            jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarreraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCorredor1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jPanelCorredor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCorredor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCorredor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(921, 921, 921)
                .addComponent(jPanelMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanelCarreraLayout.setVerticalGroup(
            jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarreraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCarreraLayout.createSequentialGroup()
                        .addComponent(jPanelCorredor1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCorredor2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCorredor3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCorredor4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        add(jPanelCarrera, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAccidente;
    public javax.swing.JButton jButtonImpulsar;
    public javax.swing.JButton jButtonIniciarCarrera;
    public javax.swing.JButton jButtonSalir;
    public javax.swing.JLabel jLabelImagenCorredor1;
    public javax.swing.JLabel jLabelImagenCorredor2;
    public javax.swing.JLabel jLabelImagenCorredor3;
    public javax.swing.JLabel jLabelImagenCorredor4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCarrera;
    public javax.swing.JPanel jPanelCorredor1;
    public javax.swing.JPanel jPanelCorredor2;
    public javax.swing.JPanel jPanelCorredor3;
    public javax.swing.JPanel jPanelCorredor4;
    public javax.swing.JPanel jPanelMeta;
    // End of variables declaration//GEN-END:variables
}
