/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.progAvUD.primerTaller2Corte.vista;

/**
 *
 * @author Andres Felipe
 */
public class PanelCarrera extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarrera
     */
    public PanelCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelCorredor4 = new javax.swing.JPanel();
        Ave = new javax.swing.JLabel();
        jPanelCorredor1 = new javax.swing.JPanel();
        Bolt = new javax.swing.JLabel();
        jPanelCorredor2 = new javax.swing.JPanel();
        Mono = new javax.swing.JLabel();
        jPanelCorredor3 = new javax.swing.JPanel();
        Leon = new javax.swing.JLabel();
        EscenarioCarrera = new javax.swing.JLabel();
        jPanelMeta = new javax.swing.JPanel();
        Mono1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonIniciarCarrera = new javax.swing.JButton();
<<<<<<< Upstream, based on origin/main
        jButtonAccidente = new javax.swing.JButton();
        jButtonImpulsar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelCorredor1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCorredor2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCorredor3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCorredor4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelMeta = new javax.swing.JPanel();
=======
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
>>>>>>> b49eb90 Modificacion Panel Carrera y agregacion de imagenes

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCorredor4.setOpaque(false);
        jPanelCorredor4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/Ave.gif"))); // NOI18N
        jPanelCorredor4.add(Ave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 120));

        jPanel2.add(jPanelCorredor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, 130));

        jPanelCorredor1.setOpaque(false);
        jPanelCorredor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bolt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/Bolt.gif"))); // NOI18N
        jPanelCorredor1.add(Bolt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 200));

        jPanel2.add(jPanelCorredor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 190, 210));

        jPanelCorredor2.setOpaque(false);
        jPanelCorredor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/Mono.gif"))); // NOI18N
        jPanelCorredor2.add(Mono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 220, 130));

        jPanel2.add(jPanelCorredor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, 130));

        jPanelCorredor3.setOpaque(false);
        jPanelCorredor3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Leon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/Leon.gif"))); // NOI18N
        jPanelCorredor3.add(Leon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jPanel2.add(jPanelCorredor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 130));

        EscenarioCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/EscenarioCarrera.png"))); // NOI18N
        jPanel2.add(EscenarioCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 650));

        jPanelMeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanelMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, 40, 476));

        Mono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/progAvUD/primerTaller2Corte/imagenes/Mono.gif"))); // NOI18N
        jPanel2.add(Mono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 120));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonIniciarCarrera.setText("Iniciar Carrera");
        jPanel1.add(jButtonIniciarCarrera);

        jButtonAccidente.setText("Accidente 1");
        jPanel1.add(jButtonAccidente);

        jButtonImpulsar.setText("Impulsar 2");
        jPanel1.add(jButtonImpulsar);

        jButtonSalir.setText("Salir");
        jPanel1.add(jButtonSalir);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1241, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< Upstream, based on origin/main
    public javax.swing.JButton jButtonAccidente;
    public javax.swing.JButton jButtonImpulsar;
=======
    private javax.swing.JLabel Ave;
    private javax.swing.JLabel Bolt;
    private javax.swing.JLabel EscenarioCarrera;
    private javax.swing.JLabel Leon;
    private javax.swing.JLabel Mono;
    private javax.swing.JLabel Mono1;
    private javax.swing.JButton Salir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
>>>>>>> b49eb90 Modificacion Panel Carrera y agregacion de imagenes
    public javax.swing.JButton jButtonIniciarCarrera;
<<<<<<< Upstream, based on origin/main
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
=======
>>>>>>> b49eb90 Modificacion Panel Carrera y agregacion de imagenes
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanelCorredor1;
    public javax.swing.JPanel jPanelCorredor2;
    public javax.swing.JPanel jPanelCorredor3;
    public javax.swing.JPanel jPanelCorredor4;
    public javax.swing.JPanel jPanelMeta;
    // End of variables declaration//GEN-END:variables
}
