package edu.progAvUD.primerTaller2Corte.vista;

import edu.progAvUD.primerTaller2Corte.control.ControlGrafico;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlGrafico controlGrafico;
    public PanelPrincipal panelPrincipal;
    public DialogDatosCorredor dialogDatosCorredor;
    public PanelCarrera panelCarrera;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        setVisible(true);
        initComponents();
        this.controlGrafico = controlGrafico;
        this.panelPrincipal = new PanelPrincipal();
        this.dialogDatosCorredor = new DialogDatosCorredor(this, true);
        this.panelCarrera = new PanelCarrera();
    }
    
    /**
     * Muestra un cuadro de diálogo con un mensaje de éxito.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de error.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * Se encarga de mostrar cada panel
     *
     * @param panel
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
